/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab2.app;



import java.io.FileNotFoundException;
import java.io.IOException;

import lab2.io.ConsoleInputManager;
import lab2.io.ConsoleOutputManager;
import lab2.io.FileInputManager;
import lab2.io.InputManager;
import lab2.io.OutputManager;

import lab2.utils.DoubleFormatter;
import lombok.Getter;
import lombok.Setter;

public class App {
    static private App instanse;
    public static App getInstanse() {
        if(instanse == null) {
            instanse = new App();
        }
        return instanse;
    }
    

    @Getter @Setter
    private InputManager in;
    @Getter 
    private OutputManager out;

    @Getter @Setter
    private boolean running;

    private App() {
        out = new ConsoleOutputManager();
        in = new ConsoleInputManager();

    }
    void print_dimka(String text, int gap){
        String d = "";
        for(int i=0;i<gap;i++){
            d=d + " ";
        }
        out.print(d + "__┌──┐__\n"+d+" (-■_■)\n"+d+" />  П    "+text+"   \n"+d+"    [X]");
    }

    public void printGreetings() {
    
        out.print("\n█▀▀ █░░█ █▀▀ ▀▀█▀▀ █▀▀ █▀▄▀█   █▀▀█ █▀▀   █░░ ░▀░ █▀▀▄ █▀▀ █▀▀█ █▀▀█ \n▀▀█ █▄▄█ ▀▀█ ░░█░░ █▀▀ █░▀░█   █░░█ █▀▀   █░░ ▀█▀ █░░█ █▀▀ █▄▄█ █▄▄▀ \n▀▀▀ ▄▄▄█ ▀▀▀ ░░▀░░ ▀▀▀ ▀░░░▀   ▀▀▀▀ ▀░░   ▀▀▀ ▀▀▀ ▀░░▀ ▀▀▀ ▀░░▀ ▀░▀▀ \n\n█▀▀ █▀▀█ █░░█ █▀▀█ ▀▀█▀▀ ░▀░ █▀▀█ █▀▀▄ █▀▀   █░█ ░▀░ █░░ █░░ █▀▀ █▀▀█ \n█▀▀ █░░█ █░░█ █▄▄█ ░░█░░ ▀█▀ █░░█ █░░█ ▀▀█   █▀▄ ▀█▀ █░░ █░░ █▀▀ █▄▄▀ \n▀▀▀ ▀▀▀█ ░▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀▀▀▀ ▀░░▀ ▀▀▀   ▀░▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀ ▀░▀▀");

        print_dimka("by @dimka_228",50);
        //out.print("\t \t \t \t \t \t \tby @dimka_228");
        out.print("\n");
        
        
    }
    
    public void start(){
       
        
        setRunning(true);
        printGreetings();
        //test();
        while (running) {
            run();
        }
  
    }
    void printSolution(){
       
       
        
    }

    public void run(){
        int cmd = in.readCommand();
      
        if(cmd == 3) {
            stop();
            return;
        }
        if(cmd == 1) {
            
            printSolution();  
        }
        else if(cmd == 2) {
            String path = in.readPath();
            try (InputManager fileInput = new FileInputManager(path)){
                
                printSolution();
            } catch(FileNotFoundException e) {
                out.error("Файл "+ path + " не найден");
            } catch (IOException e) {
                out.error("Ошибка при чтении файла " + path);
            } catch (IllegalArgumentException e) {
                out.error("Данные в файле некорректны: " + e.getMessage());
            } catch (Exception e) {
                out.error("Неизвестная ошибка");
            }
        }  
    }

    public void stop(){
        running = false;
    }


    public void exit(){
        System.exit(0);
    }


    
}
